### ISSUE TITLE
Running imvirt multiple times results in unstable and incorrect output

### ISSUE THREAD

**Issue by alexbarton** [DE-IBH/imvirt#15] opened 2015-12-29 15:56 UTC
Running `imvirt` multiple times results in unstable and incorrect output on some KVM virtual machines. Example output:

```
$ imvirt
Unknown
$ imvirt
KVM
$ imvirt
Unknown
$ imvirt
KVM
$ imvirt
KVM
$ imvirt
Unknown
```

The correct answer is *KVM* …

Probably interesting part of `imvirt-report`:

**Good**:
```
$VAR1 = {
   'KVM' => '0.653333333333333',
   'Physical' => '0.0133333333333333',
   'lguest' => '0.333333333333333'
 };

ImVirt: imv_get: m = 0.333333333333333
ImVirt: imv_get: s² = 0.1024
ImVirt: imv_get: 0.653333333333333 - sqrt(0.1024) > 0.0133333333333333
KVM
```

vs.

**Bad**:
```
ImVirt: imvirt_detect():
$VAR1 = {
   'lguest' => '0.333333333333333',                             
   'Physical' => '0.0133333333333333',
   'KVM' => '0.653333333333333'
 };
 
ImVirt: imv_get: m = 0.333333333333333                                 
ImVirt: imv_get: s² = 0.1024
ImVirt: imv_get: 0.653333333333333 - sqrt(0.1024) > 0.333333333333333  
Unknown
```

This is seconds later on the same machine.

Any ideas?

**Comment by alexbarton** [comment] 2015-12-29 16:02
Hm … probably this is a duplicate of (or at least related to) #14 – the report looks quite similar:

- `$VAR1` looks similar between runs, numbers are all the same, but the sorting differs.
- and the "greather than" test uses different numers for the _good_ vs. _bad_ case …

**Comment by liske** [comment] 2015-12-29 18:01
Hi Alex,

I think it is a duplicate of #15 ... but your details on both cases let me found the issue:

> ImVirt: imv_get: 0.653333333333333 - sqrt(0.1024) > **0.0133333333333333**

vs.

> ImVirt: imv_get: 0.653333333333333 - sqrt(0.1024) > **0.333333333333333**

The `$VAR1` hash (virtualization => probility) is sorted, the candidate with the highest probability is returned if, and only if it has enough distance to the second top-most candidate. I've looked long time and intensively on the code and everything seems to be OK. But than I realized that the sort function is broken:

```
ImVirt.pm:261    my @res = sort { $rtree{$b} > $rtree{$a} } keys %rtree;
```

should read:

```
ImVirt.pm:261    my @res = sort { $rtree{$b} <=> $rtree{$a} } keys %rtree;
```

to sort correctly!

**Closed** 2015-12-29 18:11 UTC
Labels: bug, duplicate

**Comment by alexbarton** [comment] 2015-12-29 20:42
Thanks a lot for fixing this @liske!
